# Generated by Django 4.2.16 on 2024-10-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=50)),
                ('tale_title', models.CharField(max_length=50)),
                ('tale_content', models.TextField()),
            ],
        ),
    ]
