# Generated by Django 4.2.16 on 2024-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='song_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
